### ISSUE TITLE
etherpad-loadtest script is missing!

### ISSUE THREAD

**Issue by HarryBleckert** [ether/etherpad-load-test#5]
Dear John,

the script etherpad-loadtest is missing here!

**Comment by JohnMcLear** [comment]
Ah bugger, I assumed you could have two scripts in binaries but maybe not..   will take a look tomorrow..  for now just install an older version..

You did ``npm install -g etherpad-load-test`` yeah?

**Comment by HarryBleckert** [comment]
Thanks for the quick reply.
And no, I installed using git clone.
Now I installed  using 
> npm install -g etherpad-load-test
and got the script copied to my devices local bin folder.
That was the solution.
For other dummies like me, maybe put an installation note in README.md
