### ISSUE TITLE
Add hint to run npm link before using etherpad-loadtest

### ISSUE THREAD

**Issue by simon-lund** [ether/etherpad-load-test#6]
I have not used the package.json "bin" feature before and it took me quite a while to figure out how to setup the project.
Turns out the missing piece was `npm link`. Maybe you could add this as a hint to the readme so that people can use this great tool right away.

**Comment by JohnMcLear** [comment]
I never use npm link, I tend to just install this tool globally :)  Happy to see a PR providing a better UX tho if you can send one through it'd be great.

Also great you are giving this a shot, if you hit limitations remember etherpad-proxy is a thing to rewrite to multiple backend instances 🔥

**Comment by simon-lund** [comment]
Ahhh 😅 didn't know this was in the npm repository. I just cloned the project 🙈🙈 hahaha. Thx for ur quick response :) 
I'll create a PR and try my best.

**Comment by JohnMcLear** [comment]
oooh yeah, sorry I just assume people use npm install version :D
